language: elixir
matrix:
  include:
    - otp_release: 21.0
      elixir: 1.7.2
      env: MIX_ENV=test
    - otp_release: 22.0
      elixir: 1.10.1
      env: MIX_ENV=test
after_success:
  - mix coveralls.travis
