language: elixir
matrix:
  include:
    - otp_release: 18.1
      elixir: 1.3.0
      env: MIX_ENV=test
    - otp_release: 19.2
      elixir: 1.4.0
      env: MIX_ENV=test
after_success:
  - mix coveralls.travis
